# Generated by Django 4.2.7 on 2023-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='commnet_num',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayisi'),
        ),
    ]
