# Generated by Django 4.2.7 on 2023-12-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_blog_commnet_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='commnet_num',
            new_name='comment_num',
        ),
    ]
