# Generated by Django 4.2.7 on 2023-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_rename_commnet_num_blog_comment_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Konu')),
                ('text', models.CharField(max_length=50, verbose_name='Mesaj')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('fullname', models.CharField(max_length=50, verbose_name='Ad-Soyad')),
            ],
        ),
    ]
