# Generated by Django 4.2.7 on 2023-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contact',
        ),
    ]
